1) Создать вектор (одномерный массив) размера 10, заполненный нулями.

In [2]:
import numpy as np
nulls = np.zeros(10)
print(nulls)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Создать матрицу размера 10x5, заполненную единицами.

In [20]:
ones = np.full((10,5),1)
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


3) Создать вектор размера 10, заполненный числом 2.5.

In [21]:
ones = np.full(10, 2.5)
print(ones)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


4) Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1.

In [22]:
ones = np.full(10, 2.5)
ones[4] = 1
print(ones)

[2.5 2.5 2.5 2.5 1.  2.5 2.5 2.5 2.5 2.5]


5) Создать вектор со значениями от 10 до 49 включительно.

In [51]:
from_to = np.arange(10,50)
print(from_to)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


6) Развернуть вектор из задачи 5 (первый становится последним).

In [25]:
ot_morf = from_to[::-1]
print(ot_morf)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


7) Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8.

In [26]:
from_to_mat = np.arange(0,9).reshape(3,3)
print(from_to_mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


8) Поменять местами 2 строки в произвольной матрице.

In [27]:
changed = from_to_mat.copy()
changed[[2,0]] = changed[[0,2]]
print(changed)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


9) Найти индексы ненулевых элементов в [1,2,0,0,4,0].

In [36]:
data = np.array([1,2,0,0,2,0])
zero_idx = np.where(data != 0)[0]
zridx = np.nonzero(data)[0]
print(zero_idx, zridx)

[0 1 4] [0 1 4]


10) Создать массив 3x3x3 со случайными вещественными значениями.

In [37]:
arrr = np.random.random((3,3,3))
print(arrr)

[[[0.50272312 0.53050006 0.10598733]
  [0.92469773 0.30433482 0.72456585]
  [0.26904524 0.5947553  0.87851518]]

 [[0.91643986 0.86754394 0.91022439]
  [0.24591799 0.02779738 0.85544555]
  [0.92540179 0.35995949 0.2640004 ]]

 [[0.56578577 0.28878057 0.19646902]
  [0.28538206 0.33747001 0.20410235]
  [0.25756895 0.80574897 0.65629267]]]


11) Создать массив 10x10 со случайными цедлчисленныеми [-10, 10] значениями, найти минимум и максимум.

In [55]:
arr = np.random.randint(-10, 11, (10,10))
print(arr, '\n' ,
      f''' min val {arr.min()}, max val {arr.max()}''')

[[  8  -2  -9  -2   2   8   4   1  10  -2]
 [  0   7   7  10 -10   2   3   8  -2  -8]
 [ -6  10  -5   5   9  -7   9   4  -6  -9]
 [ -1   9   0   9  -2  -4  -9 -10  -4   8]
 [ -1  10   7   5  -8  10   5  -8  -2  -7]
 [ -9   8  -9   6  -7  -6   7   1   9   8]
 [ -1   0  -8   9   5  -6   3   2   9   3]
 [-10   5   1   0   9  -8   2  -1  -7  -7]
 [ -1   6   1  -7   9   0   1   9   7   9]
 [  0   1  -6  -5  -7   7 -10  10  -5  -9]] 
  min val -10, max val 10


12) Создать случайный вектор размера 30 и найти среднее значение всех элементов.

In [45]:
expectation = np.random.random((30,)).mean()
print(expectation)

0.4996466251908763


13) Создать 5x5 матрицу с 1,2,3,4,5 на главной диагонали.

In [49]:
diag = np.diag(np.arange(1,6))
print(diag)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


14) Перемножить произвольные матрицы 5x3 и 3x2.

In [50]:
a = np.random.random((5,3))
b = np.random.random((3,2))
c = np.dot(a,b)
print(c)

[[0.7030332  1.02803162]
 [1.02522666 1.18442285]
 [1.06351289 0.98823725]
 [0.6998126  0.9827705 ]
 [0.31665263 0.70766719]]


15) Есть случайный массив из 100 элементов со значениями от 0 до 20, поменять знак у
элементов, значения которых между 3 и 8.

In [24]:
random_vect = 20 * np.random.random(10)
rv[(rv > 3) & (rv < 8)] *= -1
print(rv)

[14.79141075 12.92759776 -4.93093871 19.51678429 11.33286183 16.3106571
 11.01178015 14.13066839 -7.34685068 13.51968912 -5.25862093 13.49538671
 17.37596251 16.58715674  9.16093999  1.05022223 16.89481481 14.92406459
 19.02772243 17.59310585 -5.27794858 16.49306842  1.79685096 17.95967521
 10.76550311 -5.45528426 14.82610523 16.84852108  1.50291495 13.84898649
  8.46196356 10.92165985 -3.66059653 13.99054233 19.30101651 15.65222325
  2.53663562 17.31099977 18.29254682 19.90266745 -4.68161189 13.0986365
 18.73984036  8.87139207 -7.80475198  1.68293679 -7.72399443 10.50570448
 15.15801088 -7.5359125  15.52465485 15.86556038 -6.65871126 -4.27486005
 17.54506047 -6.60245373 -5.55737256 16.5416237  -6.52664731 10.52504852
 -6.24738532 14.12745878 -3.8089283  12.88443672  9.05833333 -6.42453949
 12.3622917  15.49268051 -3.45393294 -6.38115634  2.69895965 17.31976029
 17.74898376 -4.75651264  1.60799159 15.80873953  1.17852916  8.21234147
 -5.92969333 -4.58079917  9.45354631 18.41887534 11.4

16) Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое.

In [23]:
step = 100
zto = np.linspace(0,1,step)[1:-1]
print(zto)

[0.01010101 0.02020202 0.03030303 0.04040404 0.05050505 0.06060606
 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111 0.12121212
 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717 0.18181818
 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323 0.24242424
 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929 0.3030303
 0.31313131 0.32323232 0.33333333 0.34343434 0.35353535 0.36363636
 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141 0.42424242
 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747 0.48484848
 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354 0.54545455
 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596  0.60606061
 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566 0.66666667
 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172 0.72727273
 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778 0.78787879
 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384 0.84848485
 0.85858586 0.86868687 0.87878788 0.88888889 0.8989899  0.90909

17) Отсортировать вектор из 10 случайных элементов.

In [32]:
rand_vec = np.random.random(10)
print(rand_vec)
print(sorted(rand_vec))
for j in range(len(rand_vec) - 1):
    f = 0
    for i in range(len(rand_vec) - 1 - j):
        prev = rand_vec[i]
        nxt = rand_vec[i+1]
        if prev > nxt:
            rand_vec[i+1] = prev
            rand_vec[i] = nxt
            f = 1
        if f == 0:
            break
print(rand_vec)

[0.99624157 0.0226634  0.52685931 0.27812986 0.02756611 0.2680729
 0.35455621 0.37647646 0.53618364 0.06217555]
[0.022663398535055057, 0.027566109075179313, 0.062175552511334886, 0.26807289982353166, 0.2781298604043493, 0.3545562066796545, 0.3764764569804474, 0.5268593060281326, 0.5361836419859619, 0.9962415735369685]
[0.0226634  0.52685931 0.27812986 0.02756611 0.2680729  0.35455621
 0.37647646 0.53618364 0.06217555 0.99624157]


18) Найти ближайшее к заданному значению число в заданном массиве.

In [43]:
wanted = 12
rand_vc = 100 * np.random.random(10)
closest = rand_vc[np.argmin(abs(rand_vc - wanted))]
print(sorted(rand_vc), closest)

[22.845514530225465, 42.05036257632718, 45.61512693870904, 65.91508207374487, 66.35669313958063, 67.21862153352157, 75.65307277373911, 86.57841287010594, 88.08548883347996, 97.56972787539343] 22.845514530225465


19) Отнять среднее из каждой строки в матрице.

In [9]:
rm = 20 * np.random.random(20).reshape(4,5)
norms = rm.copy()
print(norms)
for i in range(len(norms)):
    norms[i] -= np.mean(rm[i])
print(norms)  

[[ 4.16251663 11.71501212 15.53273031 15.2897921   3.26279027]
 [ 6.57936355  7.14543321 12.97159927  6.31392873 10.67319357]
 [ 2.86399695 17.15816136  3.98975788 10.61785978 15.6370111 ]
 [ 2.00749227 15.74808972 15.81627228 12.16973893  2.0407309 ]]
9.99256828613027
8.736703667158942
10.053357414500084
9.556464818264468
[[-5.83005165  1.72244383  5.54016203  5.29722381 -6.72977802]
 [-2.15734012 -1.59127045  4.23489561 -2.42277494  1.9364899 ]
 [-7.18936046  7.10480395 -6.06359953  0.56450236  5.58365368]
 [-7.54897255  6.1916249   6.25980746  2.61327411 -7.51573392]]


20) Дан четырехмерный массив, посчитать сумму по последним двум осям.

In [17]:
rm = np.random.random(4**4).reshape(4,4,4,4)
sm = np.sum(rm, axis = (2,3))
print(rm, '\n', sm)


[[[[0.97310696 0.65286915 0.28740587 0.11880125]
   [0.58531981 0.88479538 0.60387608 0.16293562]
   [0.7903775  0.94206049 0.43163878 0.99186888]
   [0.2141574  0.58999705 0.93616392 0.83391958]]

  [[0.68589072 0.81396946 0.46443682 0.96447145]
   [0.99027974 0.19920921 0.60374576 0.64803616]
   [0.11338054 0.06955918 0.56825918 0.28614341]
   [0.51675383 0.62671409 0.18959125 0.32654644]]

  [[0.624726   0.87359247 0.69832831 0.08720738]
   [0.5147712  0.82228467 0.44928014 0.11404873]
   [0.80379387 0.99773489 0.1783575  0.68340151]
   [0.21349737 0.60226206 0.93710708 0.22188035]]

  [[0.75154465 0.74836812 0.25351994 0.87552663]
   [0.42270275 0.09660396 0.95057517 0.71513257]
   [0.63224828 0.5601342  0.56077618 0.27170486]
   [0.83658382 0.43125438 0.61873403 0.89330813]]]


 [[[0.77725828 0.42431798 0.43053985 0.81399849]
   [0.4729105  0.36126592 0.99839398 0.01685677]
   [0.2709381  0.09523867 0.5129888  0.83571206]
   [0.15201121 0.46867562 0.05423546 0.72458851]]

  [[0.67